# -*- coding: utf-8 -*-
"""Constantes de style partagées pour les rendus PDF/DOCX."""

from __future__ import annotations


# Palette BATIKAM Renov
COLOR_NAVY = "#0F2747"
COLOR_GOLD = "#C8A96B"
COLOR_BORDER = "#D9E0E7"
COLOR_SOFT = "#F7F8FA"
COLOR_SECTION = "#F5F7FA"
COLOR_TEXT = "#1F2937"
COLOR_MUTED = "#4B5563"

# Palette tableau (inspirée du modèle fourni)
COLOR_TABLE_HEADER_BG = "#1E4A78"
COLOR_TABLE_HEADER_TEXT = "#FFFFFF"
COLOR_TABLE_STRIP_BG = "#D8E0EA"
COLOR_TABLE_LOT_BG = "#F2F5F8"
COLOR_TABLE_SUBTOTAL_BG = "#E6EBF2"
COLOR_TABLE_SUBTOTAL_TEXT = "#1E4A78"
COLOR_TABLE_GRID = "#C3CDD9"


# Header tokens (PDF / DOCX)
# Header width aligned with line table width (1.1 + 10.0 + 2.0 + 2.3 + 3.1 = 18.5 cm)
HEADER_LEFT_COL_CM = 11.0
HEADER_RIGHT_COL_CM = 7.5

PDF_HEADER_LOGO_WIDTH_CM = 8.5
PDF_HEADER_LOGO_HEIGHT_CM = 5.5
PDF_HEADER_LOGO_X_OFFSET_CM = -3.5
PDF_HEADER_LOGO_BOX_HEIGHT_CM = 4.5
PDF_HEADER_GAP_LOGO_TO_COMPANY_CM = 0.02
PDF_HEADER_COMPANY_Y_OFFSET_PT = 0
PDF_HEADER_COMPANY_LEFT_INDENT_PT = 0
PDF_HEADER_COMPANY_FONT_SIZE_PT = 8.4
PDF_HEADER_COMPANY_LEADING_PT = 10.2
PDF_HEADER_SPACER_AFTER_CM = 0.02
PDF_HEADER_RIGHT_BLOCK_Y_OFFSET_PT = 7
PDF_HEADER_GAP_AFTER_CLIENT_PT = 8
PDF_HEADER_GAP_AFTER_AFFAIRE_PT = 10
PDF_SPACE_BEFORE_TABLE_CM = 0.95

DOCX_HEADER_LOGO_WIDTH_CM = 4.6
DOCX_HEADER_LOGO_HEIGHT_CM = 2.1
DOCX_HEADER_LOGO_LEFT_INDENT_PT = 0
DOCX_HEADER_GAP_LOGO_TO_COMPANY_PT = 1
DOCX_HEADER_COMPANY_Y_OFFSET_PT = 0
DOCX_HEADER_COMPANY_LEFT_INDENT_PT = 0
DOCX_HEADER_COMPANY_TITLE_FONT_PT = 9.4
DOCX_HEADER_COMPANY_FONT_PT = 8.9
DOCX_HEADER_COMPANY_LINE_AFTER_PT = 2
DOCX_HEADER_LEGAL_AFTER_PT = 8
DOCX_HEADER_DOC_BLOCK_GAP_PT = 8
DOCX_HEADER_RIGHT_BLOCK_Y_OFFSET_PT = 7
DOCX_HEADER_GAP_AFTER_CLIENT_PT = 8
DOCX_HEADER_GAP_AFTER_AFFAIRE_PT = 10
DOCX_SPACE_BEFORE_TABLE_PT = 22
DOCX_HEADER_LEFT_COL_CM = 10.4
DOCX_HEADER_RIGHT_COL_CM = 7.2
DOCX_LINE_TABLE_WIDTHS_CM = (1.0, 9.5, 1.9, 2.2, 3.0)
DOCX_CONTENT_TABLE_WIDTH_CM = sum(DOCX_LINE_TABLE_WIDTHS_CM)

# Footer tokens (DOCX)
DOCX_FOOTER_DISTANCE_CM = 0.7
DOCX_FOOTER_LINE_COLOR = COLOR_GOLD
DOCX_FOOTER_TEXT_COLOR = COLOR_MUTED
DOCX_FOOTER_LINE1_FONT_PT = 8.3
DOCX_FOOTER_LINE2_FONT_PT = 8.1
DOCX_FOOTER_LINE1_AFTER_PT = 1


# Backward compatibility for previous imports
LOGO_WIDTH_CM = PDF_HEADER_LOGO_WIDTH_CM


# Libellés harmonisés
LINE_TABLE_HEADERS = ["", "Description des travaux", "Qté", "PU HT", "Total HT"]
